spring:
  application:
    name: long-cloud-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost/eureka/
    register-with-eureka: false # 不将eureka-server作为client注册
    fetch-registry: false # 因为是单点，所以不拉取，集群要设置为true
  server:
    enable-self-preservation: false # 测试环境下不开启自我保护机制
server:
  port: 8761
